language: node_js
services:
  - mysql
before_install:
  - mysql -e 'CREATE database sabia-testing;'
  - cp packages/api/.env.example .env
install:
  - (cd packages/api && npm install)
script:
  - (cd packages/api && npm run coverage)
after_script:
  - (cd packages/api && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls)
