language: node_js

branches:
  only:
    - master
env:
  DB_DATABASE=sabia_testing
  APP_ENV=testing
  API_KEY=AIzaSyDlQrq14K2OTjUxioB4fW7NJTzZQ2ZFtxA
  
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.npm
    - ~/.cache

node_js:
  - 12

services:
  - mysql
  - redis

before_install:
  - mysql -e 'CREATE DATABASE `sabia_testing`;'
  - (cd packages/api && cp .env.ci .env)
  - (cd packages/web && cp .env.testing .env)
  - (cd packages/admin && cp .env.testing .env)

install:
  - (cd packages/api && npm install)
  - (cd packages/admin && npm install)

script:
  - (cd packages/api && npm run migration:refresh && npm run seed)
  - npm run test:e2e:run

after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
