language: node_js

branches:
  only:
    - master
node_js:
  - 12
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE `sabia-testing`;'
  - (cd packages/api && cp .env.example .env)
install:
  - npm install
  - npx lerna bootstrap
  - (cd packages/api && npm install)
script:
  - npm run lint
  - npm run build-coverage
  - (cd packages/web && npm run test:visual)
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
