language: node_js
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE sabia_ci;'
  - (cd packages/api && cp .env.example .env)
install:
  - (cd packages/api && npm install)
script:
  - (cd packages/api && npm run coverage)
after_script:
  - (cd packages/api && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls)
