version: "3.3"
services:
  web:
    ports:
      - "8000:8000"
    container_name: plataforma-sabia-web
    network_mode: plataforma-sabia
    image: run
    restart: always
    build:
      context: ./packages/web
      dockerfile: Dockerfile
  api:
    ports:
      - "3333:3333"
      - "9999:9999"
    volumes:
      - "/uploads:/plataforma-sabia/api/public"
    container_name: plataforma-sabia-api
    network_mode: plataforma-sabia
    image: run
    restart: always
    build:
      context: ./packages/api
      dockerfile: Dockerfile
  admin:
    ports:
      - "8080:80"
    container_name: plataforma-sabia-admin
    network_mode: plataforma-sabia
    image: run
    restart: always
    build:
      context: ./packages/admin
      dockerfile: Dockerfile
