# This compose file is only necessary to build web package
# Due core package that is a internal dependency
version: "3.8"

services:
  sabia-web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./packages/web/.env
    ports:
      - "8080:8080"
    command: /bin/sh -c "cd packages/web && npm start"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/web/node_modules
      - /app/packages/core/node_modules
    container_name: sabia-web
