on: [pull_request]

name: Sabia Platform - Automated tests workflow
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        node-version: [14.x]
        os: ["ubuntu-latest"]

    services:
      plataforma-sabia-redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      plataforma-sabia-mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: sabia_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore Lerna from cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: ESLint
        uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true

      - name: API tests
        working-directory: packages/api
        run: |
          cp .env.testing .env
          npm run coverage

      - name: WEB tests
        uses: mattallty/jest-github-action@v1
        working-directory: packages/web
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          test-command: "npm run jest"

      - name: Prepare API for e2e tests
        working-directory: packages/api
        run: |
          npm run migration:refresh
          npm run seed

      - name: Cypress tests
        uses: cypress-io/github-action@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          command: npm run test:e2e:coverage
          browser: chrome
          headless: true
          record: false

      - name: Prepare coverages
        run: npm run merge-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
