on:
  push:
    branches:  
    - '*'  
    - '!master'

name: Sabia Platform - Automated tests workflow
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: cd packages/web && npm install
    - run: cd packages/web && npm run jest