on:
  push:
    branches:  
    - 'master'

name: Sabia Platform - Deploy image to production/staging workflow
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services:
      plataforma-sabia-redis:
        image: redis
        ports:
        - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      plataforma-sabia-mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: sabia_testing
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd packages/api && npm install && cp .env.ci .env && npm run test
      - run: cd packages/web && npm install && npm run test

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Building and pushing the ADMIN docker image
        id: docker_build_admin
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./packages/admin/Dockerfile
          tags: plataformasabia/admin:${{ github.sha }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Building and pushing the WEB docker image
        id: docker_build_web
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./packages/web/Dockerfile
          tags: plataformasabia/web:${{ github.sha }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Building and pushing the API docker image
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./packages/api/Dockerfile
          tags: plataformasabia/api:${{ github.sha }}
      - 
        name: deploying to STAGING
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST_VPS_2 }}
          username: ${{ secrets.DEPLOY_USER_VPS_2 }}
          key: ${{ secrets.DEPLOY_KEY_VPS_2 }}
          port: ${{ secrets.DEPLOY_PORT_VPS_2 }}
          script: ./deploy-image-to-vps.sh ${{ github.sha }}
      - 
        name: deploying to PRODUCTION
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST_VPS_1 }}
          username: ${{ secrets.DEPLOY_USER_VPS_1 }}
          key: ${{ secrets.DEPLOY_KEY_VPS_1 }}
          port: ${{ secrets.DEPLOY_PORT_VPS_1 }}
          script: ./deploy-image-to-vps.sh ${{ github.sha }}