name: After server responds
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v1

    - name: Custom tests 🧪
      uses: cypress-io/github-action@v1
      with:
        command: npm run test:e2e:run